import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";



export const metadata: Metadata = {
  title: "Test3 | Root Layout",
  description: "Generated by create next app",
};


const navigations =[
  { title : "Home", href:"/"},
  {title : "About", href:"/about"},
  {title : "product", href:"/product"},
  {title : "First Page", href: "/first"}

]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div>Component Navbar</div>
        {children}
        <div>Component Footer</div>
      </body>
    </html>
  );
}
